"""The Azure DevOps operations the loop needs, as a Protocol.

`AdoClient` (REST, managed identity) implements it in production; `FakeAdo` implements it in memory for
tests, the simulator and the local loop. Anything the engine needs from Azure DevOps goes through here.
"""
from __future__ import annotations

from typing import Any, Protocol


class AdoPort(Protocol):
    def get_work_item(self, wid: int) -> dict[str, Any]: ...
    def set_tags(self, wid: int, tags: list[str]) -> None: ...
    def set_state(self, wid: int, state: str) -> None: ...
    def assign(self, wid: int, user: str) -> None: ...
    def add_comment(self, wid: int, text: str) -> None: ...
    def create_child_bug(self, parent_id: int, title: str, repro_html: str, severity: str, tags: list[str]) -> int: ...
    def open_child_bugs(self, parent_id: int) -> list[int]: ...
    def list_open_bugs(self, exclude_id: int | None = None) -> list[dict[str, Any]]: ...
    def list_loop_items(self) -> list[int]: ...
    def queue_pipeline(self, pipeline_id: int, params: dict[str, str]) -> int: ...


def tags_of(wi: dict[str, Any]) -> list[str]:
    raw = (wi.get("fields") or {}).get("System.Tags", "") or ""
    return [t.strip() for t in raw.split(";") if t.strip()]
